In [1]:
from mxnet import nd

# Scalars 

In MXNet, we work with scalars by create NDArrays with just one element.

In [4]:
x = nd.array([3.0])
y = nd.array([2.0])

print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', x ** y)

x + y =  
[5.]
<NDArray 1 @cpu(0)>
x * y =  
[6.]
<NDArray 1 @cpu(0)>
x / y =  
[1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>


We can convert any NDArray with one element to a Python float by calling its `asscalar` method. While doing this, NDArray has to stop doing anything else in order to hand the result and control flow back to Python. This will cause performance problem. **Don't** sprinkling this operation liberally throughout your code.

In [7]:
x.asscalar()

3.0

# Vectors 

In MXNet, we work with vectors via 1D NDArrays with an arbitrary number of components.

In [8]:
x = nd.arange(4)
print('x = ', x)

x =  
[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>


Access any element by indexing into NDArray:

In [9]:
x[3]


[3.]
<NDArray 1 @cpu(0)>

# Length, dimensionality and shape 

We can access the length of an NDArray by calling the Python's built-in `len()` function:

In [10]:
len(x)

4

or access it via `.shape` property:

In [11]:
x.shape

(4,)

# Matrices

We can create a matrix with n rows and m columns by specifying a shape with two components (n, m) when calling any of our favorite functions for instantiating `ndarray`.

In [13]:
A = nd.arange(20).reshape((5, 4))
A


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>

We can access the scalar elements of matrix by specifying the indices of the row and column:

In [15]:
A[4, 3]


[19.]
<NDArray 1 @cpu(0)>

Leaving indices blank via `:` takes all elements along the respective dimension:

In [18]:
A[:, 3]


[ 3.  7. 11. 15. 19.]
<NDArray 5 @cpu(0)>

We can transpose the matrix through `T`:

In [19]:
A.T


[[ 0.  4.  8. 12. 16.]
 [ 1.  5.  9. 13. 17.]
 [ 2.  6. 10. 14. 18.]
 [ 3.  7. 11. 15. 19.]]
<NDArray 4x5 @cpu(0)>

# Tensors 

Tensors give us a generic way to work with arrays with arbitrary numbers of axes. 

In [20]:
X = nd.arange(24).reshape((2, 3, 4))
X


[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>

# Basic properties of tensor arithmetic 

Scalar multiplication keeps tensors shape.

In [21]:
a = 2
x = nd.ones(3)
y = nd.zeros(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)

(3,)
(3,)
(3,)
(3,)


# Sums and means 

In [22]:
print(x)
print(x.sum())


[1. 1. 1.]
<NDArray 3 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>


In [23]:
print(A)
print(nd.sum(A))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>

[190.]
<NDArray 1 @cpu(0)>


In [26]:
print(nd.mean(A))
print(nd.sum(A) / A.size)


[9.5]
<NDArray 1 @cpu(0)>

[9.5]
<NDArray 1 @cpu(0)>


# Dot products 

In [27]:
x = nd.arange(4)
y = nd.ones(4)
print(x, y, nd.dot(x, y))


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[6.]
<NDArray 1 @cpu(0)>


Dot product equals the sum of element-wise multiplication.

In [28]:
nd.sum(x * y)


[6.]
<NDArray 1 @cpu(0)>

# Matrix-vector products 

In [29]:
nd.dot(A, x)


[ 14.  38.  62.  86. 110.]
<NDArray 5 @cpu(0)>

# Matrix-matrix multiplication

In [31]:
B = nd.ones(shape=(4, 3))
nd.dot(A, B)


[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]
 [54. 54. 54.]
 [70. 70. 70.]]
<NDArray 5x3 @cpu(0)>

# Norms 

Properties of norms:
1. ‖αA‖=|α|‖A‖
2. ‖A+B‖≤‖A‖+‖B‖
3. ‖A‖≥0
4. If  ∀i,j,aij=0 , then  ‖A‖=0

To calculate L2 norm:

In [32]:
nd.norm(x)


[3.7416573]
<NDArray 1 @cpu(0)>

To calculate L1 norm:

In [34]:
nd.sum(nd.abs(x))


[6.]
<NDArray 1 @cpu(0)>